name: DamageIndicatorsPlus
version: '${project.version}'
main: ca.rpgcraft.damageindicatorsplus.DamageIndicatorsPlus
api-version: 1.16
softdepend:
  - ProtocolLib
  - WorldGuard
  - DIWGFlags
  - PlaceholderAPI
authors: [ dsevvv ]
description: DamageIndicators premium version, comes with config and many more features!
website: github.com/dsevvv/damageindicatorsplus
commands:
  di:

